name = "gfx_core"
description = "Modular Portable Graphics Library, Core Components"
version = "0.2.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["graphics"]

project-files = ["gnat/gfx_core.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true
